services:
  postgres:
    image: postgres:17-alpine
    container_name: webdesk-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: webdesk
      POSTGRES_PASSWORD: webdesk_password
      POSTGRES_DB: webdesk

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: webdesk-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: